### ISSUE TITLE
commits benennen

### ISSUE THREAD

**Issue by LFF5644** [mattes2008/VocabularyCompanion#3]
ich gucke hier ab und zu mal vorbei sehe ohh 22 commits was neues klicke dann auf commits und sehe das die alle ähnlich bis gleich benannt sind tipp benutze immer einen anderen namen für einen commit nicht den gleichen 2mal hinterein ander und nimm schlaue namen zb optimised oder rechtschreibfehlerbehoben xD

**Comment by mattes2008** [comment]
Ich wollte sie auch nach den Changes benennen, habe mich aber dagegen entschieden, da alle der Version 1.0 angehören. Wenn neue Versionen kommen werde ich die Commits benennen.

Aber vielen Dank für den Tipp.

**Comment by LFF5644** [comment]
ich meine das wenn du was neues machst zb du fügst eine neue function hinzu dann kannst du den commt "add function <functionname>" oder so
